import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://eclassyshop.ondokan.com/admin');
  await page.goto('https://eclassyshop.ondokan.com/admin/login');
  await page.goto('https://eclassyshop.ondokan.com/admin');
  await page.goto('https://eclassyshop.ondokan.com/admin/login');
  await page.getByPlaceholder('yourname@email.com').click();
  await page.getByPlaceholder('yourname@email.com').fill('farazi@wedevs.com');
  await page.getByPlaceholder('yourname@email.com').press('ControlOrMeta+a');
  await page.getByPlaceholder('yourname@email.com').press('ControlOrMeta+c');
  await page.getByPlaceholder('••••••••').click();
  await page.getByPlaceholder('••••••••').fill('farazi@wedevs.comA1');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.locator('a').filter({ hasText: /^Products$/ }).click();
  await page.getByRole('link', { name: 'All Products' }).click();
  await page.locator('td').first().click();
  await page.getByRole('button', { name: 'Bulk Edit' }).click();
  await page.getByText('Column').click();
  await page.getByLabel('Images').check();
  await page.getByLabel('Cost Price').check();
  await page.getByLabel('SKU').check();
  await page.getByLabel('Barcode').check();
  await page.getByLabel('Tax Class').check();
  await page.getByLabel('Manage Stock').check();
  await page.getByLabel('Stock Quantity').check();
  await page.getByLabel('Low Stock Threshold').check();
  await page.getByLabel('Backorder').check();
  await page.getByLabel('Brand').check();
  await page.getByLabel('Tags').check();
  await page.getByLabel('Page Title (SEO)').check();
  await page.getByLabel('Meta Description (SEO)').check();
  await page.getByRole('cell', { name: 'TestProduct TestProduct' }).locator('div').first().click();
  await page.getByRole('cell', { name: 'TestProduct TestProduct' }).getByRole('textbox').fill('TestProduct Update');
  await page.getByRole('cell', { name: 'man', exact: true }).locator('div').nth(1).click();
  await page.getByRole('cell', { name: 'man', exact: true }).getByPlaceholder('Search').fill('Tasty Prod');
  await page.getByText('Tasty productize').click();
  await page.locator('td:nth-child(3) > .flex').dblclick();
  await page.locator('td:nth-child(3) > .flex').click();
  await page.getByRole('button', { name: 'Upload Image' }).click();
  await page.getByRole('button', { name: 'Upload Files' }).click();
  await page.locator('[id="headlessui-dialog-\\:r1o\\:"]').getByRole('img').click();
  await page.getByRole('button', { name: 'Select' }).click();
  await page.getByRole('button', { name: 'TestProduct' }).click();
  await page.getByRole('button', { name: 'TestProduct' }).click();
  await page.getByRole('row', { name: 'TestProduct Update' }).getByRole('paragraph').click();
  await page.locator('div').filter({ hasText: /^TestProduct$/ }).nth(1).fill('TestProduct update description');
  await page.getByRole('cell', { name: '5' }).getByRole('spinbutton').click();
  await page.getByRole('cell', { name: '5' }).getByRole('spinbutton').click();
  await page.getByRole('cell', { name: '5' }).getByRole('spinbutton').fill('110');
  await page.getByRole('spinbutton').nth(1).click();
  await page.getByRole('spinbutton').nth(1).fill('100');
  await page.getByRole('spinbutton').nth(2).click();
  await page.getByRole('spinbutton').nth(2).fill('71');
  await page.locator('td:nth-child(8) > .block').click();
  await page.locator('td:nth-child(8) > .block').fill('ksdhfjkhsj');
  await page.locator('td:nth-child(8) > .block').press('Tab');
  await page.locator('td:nth-child(9) > .block').fill('3423432');
  await page.locator('td:nth-child(9) > .block').press('Tab');
  await page.getByRole('cell', { name: 'Select' }).getByRole('button').click();
  await page.getByText('Reduced Rate').click();
  await page.getByRole('cell', { name: 'No', exact: true }).getByRole('button').click();
  await page.getByText('Yes').click();
  await page.getByRole('spinbutton').nth(3).click();
  await page.getByRole('spinbutton').nth(3).fill('120');
  await page.getByRole('spinbutton').nth(4).click();
  await page.getByRole('cell', { name: 'null' }).getByRole('spinbutton').fill('5');
  await page.getByRole('cell', { name: 'null' }).getByRole('spinbutton').press('Tab');
  await page.getByRole('cell', { name: 'Do not allow' }).getByRole('button').click();
  await page.getByText('Allow', { exact: true }).click();
  await page.locator('body').press('Tab');
  await page.getByText('Published').click();
  await page.locator('#root').getByText('Search').click();
  await page.getByRole('cell', { name: 'Search' }).getByRole('textbox').fill('');
  await page.getByText('silky').click();
  await page.locator('body').press('Tab');
  await page.getByPlaceholder('Search').nth(1).click();
  await page.getByPlaceholder('Search').nth(1).fill('new');
  await page.getByPlaceholder('Search').nth(1).press('Enter');
  await page.getByRole('cell', { name: 'new' }).getByRole('textbox').fill('two');
  await page.getByRole('cell', { name: 'new' }).getByRole('textbox').press('Enter');
  await page.getByRole('cell', { name: 'new two' }).getByRole('textbox').press('Tab');
  await page.getByRole('cell', { name: 'TestProduct', exact: true }).getByRole('textbox').click();
  await page.getByRole('cell', { name: 'TestProduct', exact: true }).getByRole('textbox').fill('TestProduct SEO');
  await page.getByLabel('Meta Description').fill('Description');
  await page.getByLabel('Meta Description').press('Escape');
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByText('Products updated successfully').click();
  await page.getByRole('link', { name: 'Products' }).click();
  await page.locator('td:nth-child(7)').first().click();
  await page.getByRole('link', { name: 'Edit' }).click();
  await page.getByRole('link', { name: 'Products', exact: true }).click();
  await page.getByRole('cell', { name: 'TestProduct Update' }).locator('div').first().click();
});


