import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://farazi.staging.dokandev.com/vendor/login');
  await page.getByPlaceholder('yourname@email.com').click();
  await page.getByPlaceholder('yourname@email.com').click();
  await page.getByPlaceholder('yourname@email.com').fill('farazi+vendor1@wedevs.com');
  await page.getByPlaceholder('yourname@email.com').press('ControlOrMeta+a');
  await page.getByPlaceholder('yourname@email.com').press('ControlOrMeta+c');
  await page.getByPlaceholder('••••••••').click();
  await page.getByPlaceholder('••••••••').fill('farazi+vendor1@wedevs.comA1');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.locator('a').filter({ hasText: 'Marketing' }).click();
  await page.getByRole('link', { name: 'Coupons' }).click();
  await page.getByRole('link', { name: 'Add Coupon' }).click();
  await page.getByLabel('Apply to specific products').click();
  await page.getByPlaceholder('Search Product').click();
  await page.getByPlaceholder('Search Product').fill('Sleek Soft Car Update');
  await page.getByRole('img', { name: 'Sleek Soft Car Update' }).click();
  await page.getByLabel('Sleek Soft Car Update$').uncheck();
  await page.getByText('Sleek Soft Car Update').click();
  await page.getByPlaceholder('Search Product').click();
  await page.getByPlaceholder('Search Product').click();
  await page.getByLabel('Sleek Soft Car Update$').uncheck();
  await page.getByPlaceholder('Search Product').click();
  await page.getByPlaceholder('Search Product').press('Tab');
  await page.getByLabel('Sleek Soft Car Update$').press('Enter');
  await page.getByLabel('Sleek Soft Car Update$').press('Enter');
  await page.getByLabel('Sleek Soft Car Update$').check();
  await page.getByText('Sleek Soft Car Update$').click();
  await page.getByRole('img', { name: 'Sleek Soft Car Update' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByPlaceholder('Search Category').click();
  await page.getByPlaceholder('Search Category').fill('Tasty Rolls');
  await page.getByText('Tasty Rolls').click();
  await page.getByText('Tasty Rolls1 product').click();
  await page.getByRole('button', { name: 'Add' }).click();
});